/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.ggnet.saft.sample.aux;

import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author oliver.guenther
 */
public class MainPanelAddButtons extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanelAddButtons() {
        initComponents();
    }

    public JProgressBar getProgressBar() {
        return ProgressBar;
    }

    public JPanel getButtonPanel() {
        return buttonPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        buttonPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        jLabel1.setText("The Main Application");
        add(jLabel1, java.awt.BorderLayout.CENTER);
        add(ProgressBar, java.awt.BorderLayout.PAGE_START);

        buttonPanel.setMinimumSize(new java.awt.Dimension(30, 30));
        add(buttonPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
